name: Build & Test (Windows)
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Prebuild Filename
        id: prebuild-filename
        run: echo "::set-output ARCHIVE_NAME::$github.ref-win32-x64.tar.gz"

      - name: Build Prebuild
        run: |
          echo ${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}
          npm run prebuild
          tar -zcvf "${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}" -C prebuilds .

      - name: Upload Prebuild
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}
          asset_name: v1.0.0-beta.23-test1
          tag: ${{ github.ref }}
          overwrite: true