name: Prebuild (Linux)
on:
  push:
    tags:
    - '*'

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
 
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Fetch deltachat-core-rust submodule
      run: npm run submodule
    
    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ./node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-3-${{ hashFiles('**/package.json') }}

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-2-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-2-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: deltachat-core-rust/target
        key: ${{ runner.os }}-cargo-2-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Prebuild Filename
      id: prebuild-filename
      
      run: |
        Set-Variable -Name "tag" -Value ("${{ github.ref }}").replace("refs/tags/", "")        
        echo "::set-output name=ARCHIVE_NAME::$tag-linux-x64.tar.gz"
 
    - name: Build Prebuild
      run: |
        echo ${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}
        npm run prebuildify
        tar -zcvf "${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}" -C prebuilds .

    - name: Upload Prebuild
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}
        asset_name: ${{ steps.prebuild-filename.outputs.ARCHIVE_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
